# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import csv
import time
import pandas as pd
import dask.dataframe

input_file = "en-books-dataset.csv"

start_time = time.time()
data = csv.DictReader(open(input_file))
print("csv.DictReader took %s seconds" % (time.time() - start_time))

start_time = time.time()
data = pd.read_csv('en-books-dataset.csv', sep=', ')
print("pd.read_csv took %s seconds" % (time.time() - start_time))

start_time = time.time()
data = pd.read_csv("en-books-dataset.csv", chunksize=100000)
print("pd.read_csv with chunksize took %s seconds" % (time.time() - start_time))

start_time = time.time()
data = dask.dataframe.read_csv(input_file)
print("dask.dataframe took %s seconds" % (time.time() - start_time))